version: '3.8'

name: 'exploiut-dev'

services:
  nosqldatabase:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=exploiut-db
    volumes:
      - data:/data/db
    ports:
      - 127.0.0.1:27017:27017/tcp
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
  
  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 127.0.0.1:1080:1080/tcp
      - 127.0.0.1:1025:1025/tcp

volumes:
  data:
